version: '3.8'

volumes:
  postgres_data:
  postgres_backups:

networks:
  postgres_network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_USER: MSPR
      POSTGRES_PASSWORD: MSPR
      POSTGRES_DB: NesterManDB
    ports:
      - "5432:5432"
    volumes:
      - ./NesterManDB.sql:/docker-entrypoint-initdb.d/NesterManDB.sql:ro
      - ./populateDB.sql:/docker-entrypoint-initdb.d/populateDB.sql:ro
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - postgres_network

  pg-exporter:
    image: bitnami/postgres-exporter:latest
    container_name: pg-exporter
    environment:
      POSTGRES_EXPORTER_WEB_LISTEN_ADDRESS: ":9187"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    networks:
      - postgres_network

  backup:
    image: postgres:13
    container_name: backup
    depends_on:
      - postgres
    volumes:
      - ./backups:/backup
    command: >
      bash -c "while true; do
        PGPASSWORD=$$POSTGRES_PASSWORD pg_dump -h postgres -U $$POSTGRES_USER -Fc $$POSTGRES_DB > /backup/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /backup/*.dump | head -n -2 | xargs rm -f
        sleep 60
      done"
    environment:
      POSTGRES_USER: MSPR
      POSTGRES_PASSWORD: MSPR
      POSTGRES_DB: NesterManDB
    networks:
      - postgres_network